# This file was generated by GoReleaser. DO NOT EDIT.
class Helloworld < Formula
  desc ""
  homepage ""
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tensorchen/helloworld-homebrew/releases/download/v0.2.0/helloworld_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "4922bfb64b4c63328b1824a6a6861ffafadbd414e2133eaabc78f93eab74c3a2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tensorchen/helloworld-homebrew/releases/download/v0.2.0/helloworld_0.2.0_Linux_x86_64.tar.gz"
      sha256 "a9d069253a2ba54ce57abc66ed700cd0784520c03bdeacf09a0d21e497e6dc9c"
    end
  end

  def install
    bin.install "helloworld"
  end
end
